language: python

python:
  - "3.6"     
  - "3.8"
install:
  - pip install -r requirements.txt


script: python3 anilistpy/anime.py && python3 anilistpy/anime.py && python3 anilistpy/search/anime.py && python3 anilistpy/search/manga.py && python3 anilistpy/search/char.py
